DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS feedbacks CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;
DROP TABLE IF EXISTS item_request_offers CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)        NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    available   BOOLEAN,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE

);
CREATE TABLE IF NOT EXISTS feedbacks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    item_id     BIGINT       NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGSERIAL PRIMARY KEY,
    requester_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    status       VARCHAR(32)  NOT NULL DEFAULT 'OPEN',
    created_at   TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS item_request_offers
(
    id           BIGSERIAL PRIMARY KEY,
    request_id   BIGINT      NOT NULL REFERENCES item_requests (id) ON DELETE CASCADE,
    item_id      BIGINT      NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    added_by_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    added_at     TIMESTAMP   NOT NULL DEFAULT now(),
    comment      TEXT,
    offer_status VARCHAR(32) NOT NULL DEFAULT 'PROPOSED'
);
